name: "JS Actions"

on: [push]

jobs:
  action: 
  
    runs-on: "ubuntu-latest"
    
    steps: 
      - uses: actions/checkout@v1
      
      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with: 
          first-greeting: "Hello Learning Lab User"
          second-greeting: "Hello Mona the Octacat is awesome"
          third-greeting: "Hello This is the last input"
